# Generated by Django 5.2.6 on 2025-10-10 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritoproducto',
            old_name='Producto',
            new_name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoproducto',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
